---
title: "Organization.Rmd"
author: "Ruby Huang"
date: "11/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(rstanarm)
library(rsample)
library(tidymodels)
library(readr)
library(readxl)
```

```{r}
# read in excel sheets

read_files <- function(file, year){
  read_excel(file) %>% 
    mutate(year = year)
}
```

```{r, aces}


Individual_Aces_1920 <- read_files("raw_data/Individual/NCAA Aces Per Set 2019-20.xlsx", 2019)

Individual_Aces_1617 <- read_files("raw_data/Individual/NCAA Aces Per Set 2016-17.xlsx", 2016)

Individual_Aces_1516 <- read_files("raw_data/Individual/NCAA Aces Per Set 2015-16.xlsx", 2015)

Individual_Aces_1415 <- read_files("raw_data/Individual/NCAA Aces Per Set 2014-15.xlsx", 2014)

Individual_Aces_1314 <- read_files("raw_data/Individual/NCAA Aces Per Set 2013-14.xlsx", 2013)

Individual_Aces_1112 <- read_files("raw_data/Individual/NCAA Aces Per Set 2011-12.xlsx", 2011)

Team_Aces_1112 <- read_files("raw_data/Team/NCAA Aces Per Set 2011-12.xlsx", 2011)

Team_Aces_1314 <- read_files("raw_data/Team/NCAA Aces Per Set 2013-14.xlsx", 2013) %>% 
  mutate(`W-L` = NA)

Team_Aces_1516 <- read_files("raw_data/Team/NCAA Aces Per Set 2015-16.xlsx", 2015)

Team_Aces_1617 <- read_files("raw_data/Team/NCAA Aces Per Set 2016-17.xlsx", 2016)

Team_Aces_1920 <- read_files("raw_data/Team/NCAA Aces Per Set 2019-20.xlsx", 2019)
```


```{r, assists}
# Read in all assists.


Individual_Assists_1112 <- read_files("raw_data/Individual/NCAA Assists Per Set 2011-12.xlsx", 2011) 

Individual_Assists_1314 <- read_files("raw_data/Individual/NCAA Assists Per Set 2013-14.xlsx", 2013)

Individual_Assists_1516 <- read_files("raw_data/Individual/NCAA Assists Per Set 2015-16.xlsx", 2015)

Individual_Assists_1617 <- read_files("raw_data/Individual/NCAA Assists Per Set 2016-17.xlsx", 2016)

Individual_Assists_1920 <- read_files("raw_data/Individual/NCAA Assists Per Set 2019-20.xlsx", 2019)

Team_Assists_Set_1920 <- read_files("raw_data/Team/NCAA Assists Per Set 2019-20.xlsx", 2019)

Team_Assists_Set_1617 <- read_files("raw_data/Team/NCAA Assists Per Set 2016-17.xlsx", 2016)

Team_Assists_Set_1516 <- read_files("raw_data/Team/NCAA Assists Per Set 2015-16.xlsx", 2015)

Team_Assists_Set_1314 <- read_files("raw_data/Team/NCAA Assists Per Set 2013-14.xlsx", 2013) %>% 
  mutate(`W-L` = NA)

Team_Assists_Set_1112 <- read_files("raw_data/Team/NCAA Assists Per Set 2011-12.xlsx", 2011)

Team_Assists_1415 <- read_files("raw_data/Team/NCAA Team Assists 2014-15.xlsx", 2014)

Team_Assists_1516 <- read_files("raw_data/Team/NCAA Team Assists 2015-16.xlsx", 2015)

Team_Assists_1617 <- read_files("raw_data/Team/NCAA Team Assists 2016-17.xlsx", 2016)

Team_Assists_1718 <- read_files("raw_data/Team/NCAA Team Assists 2017-18.xlsx", 2017)

Team_Assists_1920 <- read_files("raw_data/Team/NCAA Team Assists 2019-20.xlsx", 2019)
```

```{r, attacks }

Individual_Attacks_1516 <- read_files("raw_data/Individual/NCAA Attacks Per Set 2015-16.xlsx", 2015)

Individual_Attacks_1617 <- read_files("raw_data/Individual/NCAA Attacks Per Set 2016-17.xlsx", 2016)

Individual_Attacks_1920 <- read_files("raw_data/Individual/NCAA Attacks Per Set 2019-20.xlsx", 2019)

Team_Attacks_1920 <- read_files("raw_data/Team/NCAA Team Attacks Per Set 2019-20.xlsx", 2019)

Team_Attacks_1617 <- read_files("raw_data/Team/NCAA Team Attacks Per Set 2016-17.xlsx", 2016)

Team_Attacks_1516 <- read_files("raw_data/Team/NCAA Team Attacks Per Set 2015-16.xlsx", 2015)
```

```{r, blocks}

Individual_Blocks_1112 <- read_files("raw_data/Individual/NCAA Blocks Per Set 2011-12.xlsx", 2011)

Individual_Blocks_1314 <- read_files("raw_data/Individual/NCAA Blocks Per Set 2013-14.xlsx", 2013)

Individual_Blocks_1516 <- read_files("raw_data/Individual/NCAA Blocks Per Set 2015-16.xlsx", 2015)

Individual_Blocks_1617 <- read_files("raw_data/Individual/NCAA Blocks Per Set 2016-17.xlsx", 2016)

Individual_Blocks_1920 <- read_files("raw_data/Individual/NCAA Blocks Per Set 2019-20.xlsx", 2019)

Team_Blocks_1920 <- read_files("raw_data/Team/NCAA Blocks Per Set 2019-20.xlsx", 2019)

Team_Blocks_1617 <- read_files("raw_data/Team/NCAA Blocks Per Set 2016-17.xlsx", 2016)

Team_Blocks_1516 <- read_files("raw_data/Team/NCAA Blocks Per Set 2015-16.xlsx", 2015)

Team_Blocks_1314 <- read_files("raw_data/Team/NCAA Blocks Per Set 2013-14.xlsx", 2013) %>% 
  mutate(`W-L` = NA)

Team_Blocks_1112 <- read_files("raw_data/Team/NCAA Blocks Per Set 2011-12.xlsx", 2011)
```

```{r, digs}

Individual_Digs_1112 <- read_files("raw_data/Individual/NCAA Digs Per Set 2011-12.xlsx", 2011)

Individual_Digs_1314 <- read_files("raw_data/Individual/NCAA Digs Per Set 2013-14.xlsx", 2013)

Individual_Digs_1415 <- read_files("raw_data/Individual/NCAA Digs Per Set 2014-15.xlsx", 2014)

Individual_Digs_1516 <- read_files("raw_data/Individual/NCAA Digs Per Set 2015-16.xlsx", 2015)

Individual_Digs_1617 <- read_files("raw_data/Individual/NCAA Digs Per Set 2016-17.xlsx", 2016)

Individual_Digs_1920 <- read_files("raw_data/Individual/NCAA Digs Per Set 2019-20.xlsx", 2019)

Team_Digs_Set_1920 <- read_files("raw_data/Team/NCAA Digs Per Set 2019-20.xlsx", 2019)

Team_Digs_Set_1617 <- read_files("raw_data/Team/NCAA Digs Per Set 2016-17.xlsx", 2016)

Team_Digs_Set_1516 <- read_files("raw_data/Team/NCAA Digs Per Set 2015-16.xlsx", 2015)

Team_Digs_Set_1314 <- read_files("raw_data/Team/NCAA Digs Per Set 2013-14.xlsx", 2013) %>% 
  mutate(`W-L` = NA)

Team_Digs_Set_1112 <- read_files("raw_data/Team/NCAA Digs Per Set 2011-12.xlsx", 2011)
```

```{r, Hitting Percentage}

Individual_Hitting_Percentage_1112 <- read_files("raw_data/Individual/NCAA Hitting Percentage 2011-12.xlsx", 2011)

Individual_Hitting_Percentage_1314 <- read_files("raw_data/Individual/NCAA Hitting Percentage 2013-14.xlsx", 2013)

Individual_Hitting_Percentage_1516 <- read_files("raw_data/Individual/NCAA Hitting Percentage 2015-16.xlsx", 2015)

Individual_Hitting_Percentage_1617 <- read_files("raw_data/Individual/NCAA Hitting Percentage 2016-17.xlsx", 2016)

Individual_Hitting_Percentage_1920 <- read_files("raw_data/Individual/NCAA Hitting Percentage 2019-20.xlsx", 2019)

Team_Hitting_Percentage_1920 <- read_files("raw_data/Team/NCAA Hitting Percentage 2019-20.xlsx", 2019)

Team_Hitting_Percentage_1617 <- read_files("raw_data/Team/NCAA Hitting Percentage 2016-17.xlsx", 2016)

Team_Hitting_Percentage_1516 <- read_files("raw_data/Team/NCAA Hitting Percentage 2015-16.xlsx", 2015)

Team_Hitting_Percentage_1314 <- read_files("raw_data/Team/NCAA Hitting Percentage 2013-14.xlsx", 2013) %>% 
  mutate(`S` = NA,
         `W-L` = NA)

Team_Hitting_Percentage_1112 <- read_files("raw_data/Team/NCAA Hitting Percentage 2011-12.xlsx", 2011) %>% 
  mutate(`S` = NA,
         `W-L` = NA)

Team_Opp_Hitting_Percentage_1415 <- read_files("raw_data/Team/NCAA Opp Hitting Percentage 2014-15.xlsx", 2014) %>% 
  select(-`W-L`)

Team_Opp_Hitting_Percentage_1516 <- read_files("raw_data/Team/NCAA Opp Hitting Percentage 2015-16.xlsx", 2015)

Team_Opp_Hitting_Percentage_1617 <- read_files("raw_data/Team/NCAA Opp Hitting Percentage 2016-17.xlsx", 2016)

Team_Opp_Hitting_Percentage_1920 <- read_files("raw_data/Team/NCAA Opp Hitting Percentage 2019-20.xlsx", 2019)
```

```{r, kills}

Individual_Kills_1112 <- read_files("raw_data/Individual/NCAA Kills Per Set 2011-12.xlsx", 2011)

Individual_Kills_1314 <- read_files("raw_data/Individual/NCAA Kills Per Set 2013-14.xlsx", 2013)

Individual_Kills_1516 <- read_files("raw_data/Individual/NCAA Kills Per Set 2015-16.xlsx", 2015)

Individual_Kills_1617 <- read_files("raw_data/Individual/NCAA Kills Per Set 2016-17.xlsx", 2016)

Individual_Kills_1920 <- read_files("raw_data/Individual/NCAA Kills Per Set 2019-20.xlsx", 2019)

Team_Kills_Set_1920 <- read_files("raw_data/Team/NCAA Kills Per Set 2019-20.xlsx", 2019)

Team_Kills_Set_1617 <- read_files("raw_data/Team/NCAA Kills Per Set 2016-17.xlsx", 2016)

Team_Kills_Set_1516 <- read_files("raw_data/Team/NCAA Kills Per Set 2015-16.xlsx", 2015)

Team_Kills_Set_1314 <- read_files("raw_data/Team/NCAA Kills Per Set 2013-14.xlsx", 2013) %>% 
  mutate(`W-L` = NA)

Team_Kills_Set_1112 <- read_files("raw_data/Team/NCAA Kills Per Set 2011-12.xlsx", 2011)

Team_Kills_1415 <- read_files("raw_data/Team/NCAA Team Kills 2014-15.xlsx", 2014)

Team_Kills_1516 <- read_files("raw_data/Team/NCAA Team Kills 2015-16.xlsx", 2015)

Team_Kills_1617 <- read_files("raw_data/Team/NCAA Team Kills 2016-17.xlsx", 2016)

Team_Kills_1920 <- read_files("raw_data/Team/NCAA Team Kills 2019-20.xlsx", 2019)
```

```{r, points}

Individual_Points_1516 <- read_files("raw_data/Individual/NCAA Points 2015-16.xlsx", 2015)

Individual_Points_1617 <- read_files("raw_data/Individual/NCAA Points 2016-17.xlsx", 2016)

Individual_Points_1920 <- read_files("raw_data/Individual/NCAA Points 2019-20.xlsx", 2019)

```

```{r, points per set}
Individual_Points_Per_Set_1112 <- read_files("raw_data/Individual/NCAA Points Per Set 2011-12.xlsx", 2011)

Individual_Points_Per_Set_1314 <- read_files("raw_data/Individual/NCAA Points Per Set 2013-14.xlsx", 2013)

Individual_Points_Per_Set_1516 <- read_files("raw_data/Individual/NCAA Points Per Set 2015-16.xlsx", 2015)

Individual_Points_Per_Set_1617 <- read_files("raw_data/Individual/NCAA Points Per Set 2016-17.xlsx", 2016)

Individual_Points_Per_Set_1920 <- read_files("raw_data/Individual/NCAA Points Per Set 2019-20.xlsx", 2019)

```

```{r, service aces}
Individual_Service_Aces_1516 <- read_files("raw_data/Individual/NCAA Service Aces 2015-16.xlsx", 2015)

Individual_Service_Aces_1617 <- read_files("raw_data/Individual/NCAA Service Aces 2016-17.xlsx", 2016)

Individual_Service_Aces_1920 <- read_files("raw_data/Individual/NCAA Service Aces 2019-20.xlsx", 2019)

Team_Service_Aces_1920 <- read_files("raw_data/Team/NCAA Team Service Aces 2019-20.xlsx", 2019)

Team_Service_Aces_1617 <- read_files("raw_data/Team/NCAA Team Service Aces 2016-17.xlsx", 2016)

Team_Service_Aces_1516 <- read_files("raw_data/Team/NCAA Team Service Aces 2015-16.xlsx", 2015)

Team_Service_Aces_1415 <- read_files("raw_data/Team/NCAA Team Service Aces 2014-15.xlsx", 2014)
```

```{r, total assists}

Individual_Total_Assists_1516 <- read_files("raw_data/Individual/NCAA Total Assists 2015-16.xlsx", 2015)

Individual_Total_Assists_1617 <- read_files("raw_data/Individual/NCAA Total Assists 2016-17.xlsx", 2016)

Individual_Total_Assists_1920 <- read_files("raw_data/Individual/NCAA Total Assists 2019-20.xlsx", 2019)

```

```{r, total attacks}

Individual_Total_Attacks_1415 <- read_files("raw_data/Individual/NCAA Total Attacks 2014-15.xlsx", 2014)

Individual_Total_Attacks_1516 <- read_files("raw_data/Individual/NCAA Total Attacks 2015-16.xlsx", 2015)

Individual_Total_Attacks_1617 <- read_files("raw_data/Individual/NCAA Total Attacks 2016-17.xlsx", 2016)

Individual_Total_Attacks_1920 <- read_files("raw_data/Individual/NCAA Total Attacks 2019-20.xlsx", 2019)

Team_Total_Attacks_1920 <- read_files("raw_data/Team/NCAA Team Total Attacks 2019-20.xlsx", 2019)

Team_Total_Attacks_1617 <- read_files("raw_data/Team/NCAA Team Total Attacks 2016-17.xlsx", 2016)

Team_Total_Attacks_1516 <- read_files("raw_data/Team/NCAA Team Total Attacks 2015-16.xlsx", 2015)

Team_Total_Attacks_1415 <- read_files("raw_data/Team/NCAA Team Total Attacks 2014-15.xlsx", 2014) %>% 
  mutate(`W-L` = NA)

```

```{r, total blocks}

Individual_Total_Blocks_1516 <- read_files("raw_data/Individual/NCAA Total Blocks 2015-16.xlsx", 2015)

Individual_Total_Blocks_1617 <- read_files("raw_data/Individual/NCAA Total Blocks 2016-17.xlsx", 2016)

Individual_Total_Blocks_1920 <- read_files("raw_data/Individual/NCAA Total Blocks 2019-20.xlsx", 2019)

Team_Total_Blocks_1920 <- read_files("raw_data/Team/NCAA Team Total Blocks 2019-20.xlsx", 2019)

Team_Total_Blocks_1718 <- read_files("raw_data/Team/NCAA Team Total Blocks 2017-18.xlsx", 2017)

Team_Total_Blocks_1617 <- read_files("raw_data/Team/NCAA Team Total Blocks 2016-17.xlsx", 2016)

Team_Total_Blocks_1516 <- read_files("raw_data/Team/NCAA Team Total Blocks 2015-16.xlsx", 2015)

Team_Total_Blocks_1415 <- read_files("raw_data/Team/NCAA Team Total Blocks 2014-15.xlsx", 2014)
```

```{r, total digs}

Individual_Total_Digs_1516 <- read_files("raw_data/Individual/NCAA Total Digs 2015-16.xlsx", 2015)

Individual_Total_Digs_1617 <- read_files("raw_data/Individual/NCAA Total Digs 2016-17.xlsx", 2016)

Individual_Total_Digs_1920 <- read_files("raw_data/Individual/NCAA Total Digs 2019-20.xlsx", 2019)

Team_Digs_1920 <- read_files("raw_data/Team/NCAA Team Digs 2019-20.xlsx", 2019)

Team_Digs_1617 <- read_files("raw_data/Team/NCAA Team Digs 2016-17.xlsx", 2016)

Team_Digs_1516 <- read_files("raw_data/Team/NCAA Team Digs 2015-16.xlsx", 2015)

Team_Digs_1415 <- read_files("raw_data/Team/NCAA Team Digs 2014-15.xlsx", 2014)

```

```{r, total kills}

Individual_Total_Kills_1516 <- read_files("raw_data/Individual/NCAA Total Kills 2015-16.xlsx", 2015)

Individual_Total_Kills_1617 <- read_files("raw_data/Individual/NCAA Total Kills 2016-17.xlsx", 2016)

Individual_Total_Kills_1920 <- read_files("raw_data/Individual/NCAA Total Kills 2019-20.xlsx", 2019)
```

```{r, team win rates}

Team_Win_Rate_1920 <- read_files("raw_data/Team/NCAA Win Rate 2019-20.xlsx", 2019)

Team_Win_Rate_1617 <- read_files("raw_data/Team/NCAA Win Rate 2016-17.xlsx", 2016)

Team_Win_Rate_1516 <- read_files("raw_data/Team/NCAA Win Rate 2015-16.xlsx", 2015)

Team_Win_Rate_1314 <- read_files("raw_data/Team/NCAA Win Rate 2013-14.xlsx", 2013)

Team_Win_Rate_1112 <- read_files("raw_data/Team/NCAAWin Rate 2011-12.xlsx", 2011)
```

```{r, echo=FALSE}
# combining data sheets.

combine <- function(x, y){
  rbind(x, y) 
}
```


```{r, echo=FALSE}
# individual aces

Individual_Aces <- combine(Individual_Aces_1112, Individual_Aces_1314)

Individual_Aces <- combine(Individual_Aces, Individual_Aces_1415)

Individual_Aces <- combine(Individual_Aces, Individual_Aces_1516)

Individual_Aces <- combine(Individual_Aces, Individual_Aces_1617)

Individual_Aces <- combine(Individual_Aces, Individual_Aces_1920)

# Separating the player's name and the school team 
# they play for into 2 columns.

Individual_Aces <- Individual_Aces %>% 
  separate(Player, into = c("Player", "Team"), sep = ", ")
```


```{r, echo=FALSE}

# individual assists

Individual_Assists<- combine(Individual_Assists_1112, Individual_Assists_1314)

Individual_Assists <- combine(Individual_Assists, Individual_Assists_1516)

Individual_Assists <- combine(Individual_Assists, Individual_Assists_1617)

Individual_Assists <- combine(Individual_Assists, Individual_Assists_1920)

Individual_Assists <- combine(Individual_Assists, Individual_Total_Assists) %>% 
  unique()

Individual_Assists <- Individual_Assists %>% 
  separate(Player, into = c("Player", "Team"), sep = ", ")
```

```{r, echo=FALSE}

# individual attacks

Individual_Attacks <- combine(Individual_Attacks_1516, Individual_Attacks_1617)

Individual_Attacks <- combine(Individual_Attacks, Individual_Attacks_1920) %>% 
  rename(Total = "Total Attacks")

Individual_Attacks <- combine(Individual_Attacks, Individual_Total_Attacks) %>% 
  unique()

Individual_Attacks <- Individual_Attacks %>% 
  separate(Player, into = c("Player", "Team"), sep = ", ")
```


```{r, echo=FALSE}
# individual blocks

Individual_Blocks <- combine(Individual_Blocks_1112, Individual_Blocks_1314)

Individual_Blocks <- combine(Individual_Blocks, Individual_Blocks_1516)

Individual_Blocks <- combine(Individual_Blocks, Individual_Blocks_1617)

Individual_Blocks <- combine(Individual_Blocks, Individual_Blocks_1920)
```

```{r, echo=FALSE}
# individual digs

Individual_Digs <- combine(Individual_Digs_1112,
                           Individual_Digs_1314)

Individual_Digs <- combine(Individual_Digs,
                           Individual_Digs_1415)

Individual_Digs <- combine(Individual_Digs,
                           Individual_Digs_1516)

Individual_Digs <- combine(Individual_Digs,
                           Individual_Digs_1617)

Individual_Digs <- combine(Individual_Digs,
                           Individual_Digs_1920)

Individual_Digs <- combine(Individual_Digs,
                           Individual_Total_Digs) %>% 
  unique()

Individual_Digs <- Individual_Digs %>% 
  separate(Player, into = c("Player", "Team"), sep = ", ")
```

```{r, echo=FALSE}

# individual hitting percentage

Individual_Hitting_Percentage <- combine(Individual_Hitting_Percentage_1112,                                  Individual_Hitting_Percentage_1314)

Individual_Hitting_Percentage <- combine(Individual_Hitting_Percentage,                                  Individual_Hitting_Percentage_1516)

Individual_Hitting_Percentage <- combine(Individual_Hitting_Percentage,                                  Individual_Hitting_Percentage_1617)

# Separating player's name and team and conference into two separate columns.

Individual_Hitting_Percentage <- combine(Individual_Hitting_Percentage,                                  Individual_Hitting_Percentage_1920) %>% 
  separate(Player, into = c("Player", "Team"), sep = ", ")



```

```{r, echo=FALSE}
# Individual kills

Individual_Kills <- combine(Individual_Kills_1112,
                            Individual_Kills_1314)

Individual_Kills <- combine(Individual_Kills,
                            Individual_Kills_1516)

Individual_Kills <- combine(Individual_Kills,
                            Individual_Kills_1617)

Individual_Kills <- combine(Individual_Kills,
                            Individual_Kills_1920) %>% 
  mutate(MP = NA)

Individual_Kills <- combine(Individual_Kills,
                            Individual_Total_Kills) %>% 
  unique()

Individual_Kills <- Individual_Kills %>% 
  separate(Player, into = c("Player", "Team"), sep = ", ")
```

```{r, echo=FALSE}
# individual points

Individual_Points <- combine(Individual_Points_1516,
                             Individual_Points_1617)

# Here I am adding columns S (number of sets played) and Per Set
# (average number of points scored per set by the player)
# to prepare for a merge of the Per Set and generic data.

Individual_Points <- combine(Individual_Points,
                             Individual_Points_1920) %>% 
  mutate(S = NA, "Per Set" = NA)

# Here I am merging the two data sets because not all seasons
# were available for one or the other set, and so by adding
# columns and merging them I am able to retrieve more data.

Individual_Points <- combine(Individual_Points, Individual_Points_Per_Set) %>% 
  unique() %>% 
  
# Separating player name and team+conference name.
  
  separate(Player, into = c("Player", "Team"), sep = ", ")
```

```{r, echo=FALSE}
# individual points per set

Individual_Points_Per_Set <- combine(Individual_Points_Per_Set_1112, Individual_Points_Per_Set_1314)

Individual_Points_Per_Set <- combine(Individual_Points_Per_Set, Individual_Points_Per_Set_1516)

Individual_Points_Per_Set <- combine(Individual_Points_Per_Set, Individual_Points_Per_Set_1617)

# Here I am adding a new column Pts, which equals to the 
# total number of points the player has scored that season,
# rounded to the first decimal place.
# This will prepare the per set data set for a merge with the
# generic points data set above.

Individual_Points_Per_Set <- combine(Individual_Points_Per_Set, Individual_Points_Per_Set_1920) %>% 
  mutate(Pts = round((`Per Set` * S), 1))
```

```{r, echo=FALSE}
# individual service aces

Individual_Service_Aces <- combine(Individual_Service_Aces_1516, Individual_Service_Aces_1617)

# Here I am adding a column "Per Set" for the average number
# of service aces the ranked player has per set, and I am
# rounding to 2 decimal places to match with the Per Set data set.

Individual_Service_Aces <- combine(Individual_Service_Aces, Individual_Service_Aces_1920) %>% 
  mutate("Per Set" = round(Aces/S, 2)) 

Individual_Service_Aces <- Individual_Service_Aces %>% 
  separate(Player, into = c("Player", "Team"), sep = ", ")
```

```{r, echo=FALSE}
# individual total assists

Individual_Total_Assists <- combine(Individual_Total_Assists_1516, Individual_Total_Assists_1617)

# Here I am adding a column "Per Set" for the average number
# of assists the ranked player has per set 

Individual_Total_Assists <- combine(Individual_Total_Assists, Individual_Total_Assists_1920) %>% 
  mutate("Per Set" = round(Assists/S, digits = 2))
```

```{r, echo=FALSE}
# individual total attacks

Individual_Total_Attacks <- combine(Individual_Total_Attacks_1415, Individual_Total_Attacks_1516)

Individual_Total_Attacks <- combine(Individual_Total_Attacks, Individual_Total_Attacks_1617)

Individual_Total_Attacks <- combine(Individual_Total_Attacks, Individual_Total_Attacks_1920) %>% 
  rename(Total = "Total Attacks") %>% 
  mutate("Per Set" = round(Total/S, 2))
```

```{r, echo=FALSE}
# individual total blocks

Individual_Total_Blocks <- combine(Individual_Total_Blocks_1516, Individual_Total_Blocks_1617)

# Here I am adding a column "Per Set" for the average number
# of blocks the ranked player has per set, and I am
# rounding to 2 decimal places to match with the Per Set data set.

Individual_Total_Blocks <- combine(Individual_Total_Blocks, Individual_Total_Blocks_1920) %>% 
  rename("Total" = "Site") %>% 
  mutate("Per Set" = round(Total/S, digits = 2))

Individual_Blocks <- combine(Individual_Total_Blocks,
                             Individual_Blocks) %>% 
  unique() 

Individual_Blocks <- Individual_Blocks %>% 
  separate(Player, into = c("Player", "Team"), sep = ", ")
  
```

```{r, echo=FALSE}
# individual total digs

Individual_Total_Digs <- combine(Individual_Total_Digs_1516, Individual_Total_Digs_1617)

# Here I am adding a column "Per Set" for the average number
# of digs the ranked player has per set, and I am
# rounding to 2 decimal places to match with the Per Set data set.

Individual_Total_Digs <- combine(Individual_Total_Digs, Individual_Total_Digs_1920) %>% 
  mutate("Per Set" = round(Digs/S, 2))
```

```{r, echo=FALSE}
# Individual total kills

Individual_Total_Kills <- combine(Individual_Total_Kills_1516, Individual_Total_Kills_1617)

# Here I am adding a column "Per Set" for the average number
# of kills the ranked player has per set, and I am
# rounding to 2 decimal places to match with the Per Set data set.

Individual_Total_Kills <- combine(Individual_Total_Kills, Individual_Total_Kills_1920) %>% 
  mutate("Per Set" = round(Kills/S, digits = 2))
```

```{r, echo=FALSE}
# Team aces per set

Team_Aces <- combine(Team_Aces_1112,
                     Team_Aces_1314)

Team_Aces <- combine(Team_Aces,
                     Team_Aces_1516)

Team_Aces <- combine(Team_Aces,
                     Team_Aces_1617)

Team_Aces <- combine(Team_Aces,
                     Team_Aces_1920)
```

```{r, echo=FALSE}

# team assists per set

 Team_Assists_Set <- combine(Team_Assists_Set_1112,
                            Team_Assists_Set_1314)

Team_Assists_Set <- combine(Team_Assists_Set,
                            Team_Assists_Set_1516)

Team_Assists_Set <- combine(Team_Assists_Set,
                            Team_Assists_Set_1617)

Team_Assists_Set <- combine(Team_Assists_Set,
                            Team_Assists_Set_1920)

# team assists

Team_Assists <- combine(Team_Assists_1415,
                        Team_Assists_1516)

Team_Assists <- combine(Team_Assists,
                        Team_Assists_1617)

Team_Assists <- combine(Team_Assists,
                        Team_Assists_1718)

# I am adding a new column Per Set (average number of assists
# per set played) to prepare the generic data set for a merge
# with the specified per set data set.

Team_Assists <- combine(Team_Assists,
                        Team_Assists_1920) %>% 
  mutate("Per Set" = round(Assists/S, 2))

# Here I am combining the two to retrieve more data since not
# all seasons were available for each data set. I am also
# using unique() to avoid any repetition of data.

Team_Assists <- combine(Team_Assists, Team_Assists_Set) %>% 
  unique()
```

```{r, echo=FALSE}
# Team blocks

Team_Blocks <- combine(Team_Blocks_1112,
                       Team_Blocks_1314)

Team_Blocks <- combine(Team_Blocks,
                       Team_Blocks_1516)

Team_Blocks <- combine(Team_Blocks,
                       Team_Blocks_1617)

Team_Blocks <- combine(Team_Blocks,
                       Team_Blocks_1920) %>% 
  
# Here I am adding a new column Total, which equals the total
# number of blocks to prepare for a merge with the generic
# data set.
  
  mutate(Total = round(`Per Set`*S, 1))

# Here I am combining the two data sets to retrieve more data,
# and using unique() to avoid any repeated data points.

Team_Blocks <- combine(Team_Blocks, Team_Total_Blocks) %>% 
  unique()

# team total blocks

Team_Total_Blocks <- combine(Team_Total_Blocks_1415,
                             Team_Total_Blocks_1516)

Team_Total_Blocks <- combine(Team_Total_Blocks,
                             Team_Total_Blocks_1617)

Team_Total_Blocks <- combine(Team_Total_Blocks,
                             Team_Total_Blocks_1718)

Team_Total_Blocks <- combine(Team_Total_Blocks,
                             Team_Total_Blocks_1920) %>% 
  
# Here I am renaming Site to Total as it is meant to be
# the total number of blocks by each team, but Site is an 
# unclear name.
  
  rename(Total = Site)
  
# Here I am adding a new column Per Set to prepare for a merge
# with the specific per set data set.

  Team_Total_Blocks <- Team_Total_Blocks %>% 
  mutate("Per Set" = round(Total/S, 2))
```

```{r, echo=FALSE}
# team digs

Team_Digs <- combine(Team_Digs_1415, Team_Digs_1516)

Team_Digs <- combine(Team_Digs, Team_Digs_1617)

Team_Digs <- combine(Team_Digs, Team_Digs_1920) %>% 
  mutate("Per Set" = round(Digs/S, digits = 2))

# team digs per set

Team_Digs_Set <- combine(Team_Digs_Set_1112,
                         Team_Digs_Set_1314)

Team_Digs_Set <- combine(Team_Digs_Set,
                         Team_Digs_Set_1516)

Team_Digs_Set <- combine(Team_Digs_Set,
                         Team_Digs_Set_1617)

Team_Digs_Set <- combine(Team_Digs_Set,
                         Team_Digs_Set_1920)


Team_Digs_Set <- combine(Team_Digs_Set,
                         Team_Digs) %>% 
  unique()
```

```{r, echo=FALSE}
# team hitting percentage

Team_Hitting_Percentage <- combine(Team_Hitting_Percentage_1112,                                  Team_Hitting_Percentage_1314)

Team_Hitting_Percentage <- combine(Team_Hitting_Percentage,                                  Team_Hitting_Percentage_1516)

Team_Hitting_Percentage <- combine(Team_Hitting_Percentage,                                  Team_Hitting_Percentage_1617)

Team_Hitting_Percentage <- combine(Team_Hitting_Percentage,                                  Team_Hitting_Percentage_1920)

# team opp hitting percentage

Team_Opp_Hitting_Percentage <- combine(Team_Opp_Hitting_Percentage_1415, Team_Opp_Hitting_Percentage_1516)

Team_Opp_Hitting_Percentage <- combine(Team_Opp_Hitting_Percentage, Team_Opp_Hitting_Percentage_1617)

Team_Opp_Hitting_Percentage <- combine(Team_Opp_Hitting_Percentage, Team_Opp_Hitting_Percentage_1920)


```

```{r, echo=FALSE}
# team kills

Team_Kills <- combine(Team_Kills_1415, Team_Kills_1516)

Team_Kills <- combine(Team_Kills, Team_Kills_1617)

# I am adding a new column Per Set (average number of kills
# per set played) to prepare the generic data set for a merge
# with the specified per set data set.

Team_Kills <- combine(Team_Kills, Team_Kills_1920) %>% 
  mutate("Per Set" = round(Kills/S, 2))


# Here I am combining the two to retrieve more data since not
# all seasons were available for each data set. I am also
# using unique() to avoid any repetition of data.

Team_Kills <- combine(Team_Kills, Team_Kills_Set) %>% 
  unique()

# team kills per set

Team_Kills_Set <- combine(Team_Kills_Set_1112,
                          Team_Kills_Set_1314)

Team_Kills_Set <- combine(Team_Kills_Set,
                          Team_Kills_Set_1516)

Team_Kills_Set <- combine(Team_Kills_Set,
                          Team_Kills_Set_1617)

Team_Kills_Set <- combine(Team_Kills_Set,
                          Team_Kills_Set_1920)


```

```{r, echo=FALSE}
# team service aces

Team_Service_Aces <- combine(Team_Service_Aces_1415,
                             Team_Service_Aces_1516)

Team_Service_Aces <- combine(Team_Service_Aces,
                             Team_Service_Aces_1617)

Team_Service_Aces <- combine(Team_Service_Aces,
                             Team_Service_Aces_1920)

```

```{r, echo=FALSE}
# team total attacks

Team_Total_Attacks <- combine(Team_Total_Attacks_1415,
                              Team_Total_Attacks_1516)

Team_Total_Attacks <- combine(Team_Total_Attacks,
                              Team_Total_Attacks_1617)

# I am adding a new column Per Set (average number of attacks
# per set played) to prepare the generic data set for a merge
# with the specified per set data set.

# I am first renaming the column Total Attacks to Total for
# ease of mutating.

Team_Total_Attacks <- combine(Team_Total_Attacks,
                              Team_Total_Attacks_1920) %>% 
  rename(Total = "Total Attacks") %>% 
  mutate("Per Set" = round(Total/S, 2))

# team attacks

Team_Attacks <- combine(Team_Attacks_1516,
                        Team_Attacks_1617)

Team_Attacks <- combine(Team_Attacks,
                        Team_Attacks_1920) %>% 
  rename(Total = "Total Attacks")

# Here I am combining the two data sets to retrieve more data
# since not all seasons (years) were available for the data 
# sets. I am also using unique() for only distinct results.

Team_Attacks <- combine(Team_Attacks, Team_Total_Attacks) %>%  unique()

```


```{r, echo=FALSE}
# team win rate

Team_Win_Rate <- combine(Team_Win_Rate_1112,
                         Team_Win_Rate_1314)

Team_Win_Rate <- combine(Team_Win_Rate,
                         Team_Win_Rate_1516)

Team_Win_Rate <- combine(Team_Win_Rate,
                         Team_Win_Rate_1617)

Team_Win_Rate <- combine(Team_Win_Rate,
                         Team_Win_Rate_1920)


```

```{r}
fit_1 <- lm(Aces ~ Pos + Cl,
            data = Individual_Aces)

fit_2 <- lm(Kills ~ Pos + Cl,
            data = Individual_Kills)

summary(fit_2)
```


```{r}
# create RDS file.


write_rds(Team_Aces, "raw_data/Team A.rds")

write_rds(Team_Assists, "raw_data/Team AST.rds")

write_rds(Team_Hitting_Percentage, "raw_data/Team Ht Pct.rds")

write_rds(Team_Opp_Hitting_Percentage, "raw_data/Team Opp Ht Pct.rds")

write_rds(Team_Blocks, "raw_data/Team B.rds")

write_rds(Team_Digs_Set, "raw_data/Team D.rds")

write_rds(Team_Service_Aces, "raw_data/Team SA.rds")

write_rds(Team_Win_Rate, "raw_data/Team WR.rds")

write_rds(Team_Kills, "raw_data/Team K.rds")

write_rds(Team_Attacks, "raw_data/Team Att.rds")

write_rds(Individual_Blocks, "raw_data/Individual B.rds")

write_rds(Individual_Assists, "raw_data/Individual AST.rds")

write_rds(Individual_Aces, "raw_data/Individual A.rds")

write_rds(Individual_Kills, "raw_data/Individual K.rds")

write_rds(Individual_Attacks, "raw_data/Individual Att.rds")

write_rds(Individual_Service_Aces, "raw_data/Individual SA.rds")

write_rds(Individual_Digs, "raw_data/Individual D.rds")

write_rds(Individual_Points, "raw_data/Individual Pts.rds")

write_rds(Individual_Hitting_Percentage, "raw_data/Individual Ht Pct.rds")
```



